### ISSUE TITLE
test problems

### ISSUE THREAD

**Issue by unknowone** [haibao-yu/FFNet-VIC3D#1]
hey, thanks for sharing such a great work! I have some questions about the config files. Here are some codes in config file.
```
data_info_train_path='./data/dair-v2x/flow_data_jsons/example_flow_data_info_train_2.json'
data_info_val_path='./data/dair-v2x/flow_data_jsons/example_flow_data_info_val_2.json'
```
I wonder what is in these two files, I don't get these two files after downloading the datasets. can u give me some examples or advice.
lots of thanks!
my email: yyxu893636842@gmail.com

**Comment by haibao-yu** [comment]
we have uploaded the json files in https://github.com/haibao-yu/FFNet-VIC3D/tree/main/data/dair-v2x/flow_data_jsons.
Thanks for you attenttion.
