### ISSUE TITLE
About the affine transformation in mmdet3d 1.2.0

### ISSUE THREAD

**Issue by lbin** [haibao-yu/FFNet-VIC3D#10]
https://github.com/haibao-yu/FFNet-VIC3D/blob/3f780a16affb432a327c619a7dcdbbdf906a9ff8/mmdet3d/models/detectors/v2x_voxelnet.py#L174-L182

Due to use different coords in version 1.2.0, Should I modify the r and t Here?

**Comment by lbin** [comment]
@haibao-yu Could you give me some suggestions about how to use inf2veh trans matrix generate feature trans?

**Comment by haibao-yu** [comment]
Thank you for your question.

This transformation is employed to convert a feature from the infrastructure-side feature coordinate system to the vehicle-side feature coordinate system. The process encompasses various coordinate systems, including the infrastructure-side feature coordinate system, infrastructure-side LiDAR coordinate system, vehicle-side feature coordinate system, and vehicle-side LiDAR coordinate system.

Regarding the version concern you raised, we have been utilizing v0.17.1. We recommend visualizing the transformed feature to assess the relative positional relationship between the two versions. With the help of visualization, you can make necessary adjustments to the transformation as needed.

**Comment by lbin** [comment]
Thanks for your reply~
