### ISSUE TITLE
json文件基本对不上

### ISSUE THREAD

**Issue by xuxian-0205** [haibao-yu/FFNet-VIC3D#13]
SPD的数据集没有单独的process程序，只能从DAIR-C的process改，改吧还发现混进去几个错误的json，没有对应的文件，数据集里面006xxx.json开始不连续了，从61xx跳到67xx。

**Comment by Zhh512** [comment]
请问错误的json你是怎么解决的啊？我也遇到了这个问题，我用的dair-c也有这个问题

![image](https://github.com/haibao-yu/FFNet-VIC3D/assets/73172804/41e0bc61-0821-4f32-b6f2-dc5de937018f)

**Comment by haibao-yu** [comment]
> SPD的数据集没有单独的process程序，只能从DAIR-C的process改，改吧还发现混进去几个错误的json，没有对应的文件，数据集里面006xxx.json开始不连续了，从61xx跳到67xx。

Thanks for your questions. I have provided the data process scripts, flow jsons, trained checkpoints for V2X-Seq-SPD:

- [data preprocess for V2X-Seq-SPD](https://github.com/haibao-yu/FFNet-VIC3D/tree/main/data/v2x-seq)
- [flow_jsons](https://github.com/haibao-yu/FFNet-VIC3D/tree/main/data/v2x-seq/flow_data_jsons)
- [ffnet-v2x-spd.pth](https://drive.google.com/file/d/1k-WIcGvGY4YF02ITMTTIDdPblA2cjaji/view?usp=sharing) 
- [ffnet-pretrained-v2x-spd.pth](https://drive.google.com/file/d/1LZACi8OLEVvFqz7bjsTwo0-Y_Imbp4sK/view?usp=sharing)

**Comment by haibao-yu** [comment]
> 请问错误的json你是怎么解决的啊？我也遇到了这个问题，我用的dair-c也有这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/73172804/293708085-41e0bc61-0821-4f32-b6f2-dc5de937018f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzg3MjcsIm5iZiI6MTcwNTA3ODQyNywicGF0aCI6Ii83MzE3MjgwNC8yOTM3MDgwODUtNDFlMGJjNjEtMDgyMS00ZjMyLWI2ZjItZGM1ZGU5MzcwMThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2NTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNjRlNDg5NTE3NzYwNDIzY2MwMjMxMGI3ZTYyNTViZjFlZGY2Mjk2NjM5YTQwODAzNWZhZjk2MzgyMWY4NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kHdSYB9KcAb0uSwGTh1OgOoS66Mqxi3aIcR8lbgOfd4)

Thanks for your usage and valuable feedback. There is case is a problematic pair in the release dataset. For convenience, we directly skip this problematic pair, and the preprocessing code has been updated. Please refer to the updated [preprocess for dair-v2x-c](https://github.com/haibao-yu/FFNet-VIC3D/blob/main/data/dair-v2x/preprocess.py).
