### ISSUE TITLE
The 'OpenDAIRV2X.'Links inactive.

### ISSUE THREAD

**Issue by deyang2000** [haibao-yu/FFNet-VIC3D#14]
Please refer [OpenDAIRV2X](https://github.com/AIR-THU/DAIR-V2X/configs/vic3d/middle-fusion-pointcloud/ffnet/README.md) for evaluating FFNet with OpenDAIRV2X.

The link is inactive.

**Comment by haibao-yu** [comment]
Thanks for your reminder. The link has been updated.
