### ISSUE TITLE
You should split the data_info_new.json generated from preprocessing into train/val.

### ISSUE THREAD

**Issue by fanwu66** [haibao-yu/FFNet-VIC3D#5]
120 ## You should split the data_info_new.json generated from preprocessing into train/val. 
您好！请问frame_pair_generation.py中这句话怎么具体实现，我好像没有在FFNet-VIC3D中找到有关代码

**Comment by haibao-yu** [comment]
Hi, we add split function, please see commit 3f780a16affb432a327c619a7dcdbbdf906a9ff8.

**Comment by fanwu66** [comment]
> Hi, we add split function, please see commit [3f780a1](https://github.com/haibao-yu/FFNet-VIC3D/commit/3f780a16affb432a327c619a7dcdbbdf906a9ff8).

Thanks!
