### ISSUE TITLE
Infrastructure-side id:006315 data missing problem.

### ISSUE THREAD

**Issue by DeepPhysicVision** [haibao-yu/FFNet-VIC3D#6]
Dear author,

Hello,! When running the prosssing.py, it exists a data missing problem in infrastructure-side of id 006315. After checking, we can delete it in the DAIR-V2X\cooperative-vehicle-infrastructure\cooperative\data_info.json file.
Hope for further updating, thanks!

Seven

![f547a3b172788b61ffc142e68ab5e0d](https://user-images.githubusercontent.com/36235155/229334251-4967e0ad-0a82-4eab-b178-454d11b965d5.png)
![008d3947a23f7bddfc5c6ecada6e4f9](https://user-images.githubusercontent.com/36235155/229334254-f5b03ade-9468-4910-85c8-1e2929f6d6bc.png)

**Comment by haibao-yu** [comment]
Hi, Jiaqian, thanks for your feedback. You can just skip this error file.
