### ISSUE TITLE
about the affine transformation

### ISSUE THREAD

**Issue by zjr-bit** [haibao-yu/FFNet-VIC3D#7]
Hi, thanks for your great work.
Recently, I'm reading your code, and I can't get the meaning of these codes.
https://github.com/haibao-yu/FFNet-VIC3D/blob/3f780a16affb432a327c619a7dcdbbdf906a9ff8/mmdet3d/models/detectors/v2x_voxelnet.py#L174-L182
I don't understand why these are complex, and may I overlook some important things?
Could you please give me some hints?  Thanks in Advance!

**Comment by goodgamemaker** [comment]
Hi, why do I always report a lot of errors when configuring the environment according to the readme , and even using the provided docker still cannot run successfully? How did you install it?

**Comment by zjr-bit** [comment]
Hi, I just follow the readme as below
First install pytorch.
Then `pip install --upgrade git+https://github.com/klintan/pypcd.git`
At last, 
```pip install torchvision==0.10.0
pip install mmcv-full==1.3.14
pip install mmdet==2.14.0
pip install mmsegmentation==0.14.1
cd FFNET-VIC3D && pip install -e . ```

**Comment by goodgamemaker** [comment]
Well, thank you. I  make mistakes even at this step ：
pip install mmcv-full==1.3.14

**Comment by jileimao** [comment]
@zjr-bit  There are two important points. First, the coordinates of features and the real world are different in units, so the rotation matrix of the real world needs to be mapped to the feature world. Secondly, there are also some constraints when using the F.affine_grid() function for feature translation and rotation. You can refer to Pytorch's introduction for details.

**Comment by jileimao** [comment]
@zjr-bit  There are two important points. First, the coordinates of features and the real world are different in units, so the rotation/translation matrix of the real world needs to be mapped to the feature world. Secondly, there are also some constraints when using the F.affine_grid() function for feature translation and rotation. You can refer to Pytorch's introduction for details

**Comment by zjr-bit** [comment]
@jileimao Thanks for your reply. I get it!
By the way, is there a problem about the code? 
https://github.com/haibao-yu/FFNet-VIC3D/blob/3f780a16affb432a327c619a7dcdbbdf906a9ff8/data/dair-v2x/preprocess.py#L45
I think it should be
` rotation = rotation_2 * rotation_1`
Could you please give a check? Thanks

**Comment by jileimao** [comment]
You are right, I will inform my colleagues and correct it. Thank you for your comment.

**Comment by haibao-yu** [comment]
> @jileimao Thanks for your reply. I get it! By the way, is there a problem about the code?
> 
> https://github.com/haibao-yu/FFNet-VIC3D/blob/3f780a16affb432a327c619a7dcdbbdf906a9ff8/data/dair-v2x/preprocess.py#L45
> 
> I think it should be
> ` rotation = rotation_2 * rotation_1`
> Could you please give a check? Thanks

Thanks for your valuable feedback and we have fixed this issue. Note that we trained the model based on the correct operation, so you can still use the original checkpoint that we provide. By the way, more than 95% of the relative difference between the rotation_1 * rotation_2 and rotation_2 * rotation_1 is less than 5%, and we train two different models on different rotations (rotation_1 * rotation_2 and rotation_2 * rotation_1) and the two models behave similar.
