### ISSUE TITLE
The results of the two evaluation methods are not the same

### ISSUE THREAD

**Issue by YWonchall** [haibao-yu/FFNet-VIC3D#8]
Hi, thank you for your open source work.
when I evaluate the model with MMDetection3d tools, I got the result as follows: 
<img width="383" alt="image" src="https://github.com/haibao-yu/FFNet-VIC3D/assets/56541797/c0cbcd53-25ea-4927-a1d2-558ec27b69e5">
But when I evaluate it with the command provided in this project, I got the same results as the paper.
```
# modify the DATA to point to DAIR-V2X-C-Example in script ${OpenDAIRV2X_root}/v2x/scripts/lidar_feature_flow.sh
# bash scripts/lidar_feature_flow.sh [YOUR_CUDA_DEVICE] [YOUR_FFNET_WORKDIR] [DELAY_K] 
cd ${OpenDAIRV2X_root}/v2x
bash scripts/lidar_feature_flow.sh 0 /home/yuhaibao/FFNet-VIC3D 2
```
These two use the same validation set(or not?), so why are the results inconsistent?
Thank you for your answer!

**Comment by Sunshine8921** [comment]
the same as me

**Comment by 2017904315** [comment]
Hello, I have encountered the same problem, and I would like to ask how you finally solved it. Thank you and look forward to your reply.
